export const SEND_MAIL = "SEND_MAIL";
export const SEND_MAIL_SERVER_RESPONSE_ERROR =
  "SEND_MAIL_SERVER_RESPONSE_ERROR";
export const SEND_MAIL_SERVER_RESPONSE_SUCCESS =
  "SEND_MAIL_SERVER_RESPONSE_SUCCESS";
